# Generated by Django 4.2.5 on 2023-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_members_team_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
