# Generated by Django 4.2.5 on 2023-09-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_creation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='description',
        ),
    ]
