# Generated by Django 4.2.5 on 2023-09-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='desc',
            new_name='description',
        ),
    ]
