# Generated by Django 4.2.5 on 2023-09-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_team_board_team_id_rename_board_task_board_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='board_id',
            new_name='board',
        ),
    ]
