# Generated by Django 4.2.5 on 2023-09-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_team_id_board_team_rename_board_id_task_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='team',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='board',
            new_name='board_id',
        ),
    ]
