# Generated by Django 4.2.5 on 2023-09-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_team_board_team_id_rename_board_task_board_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='team_id',
        ),
    ]
