# Generated by Django 4.2.5 on 2023-09-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_user_task_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='desc',
            new_name='description',
        ),
    ]
